library: ~/Music/library.db
directory: ~/Music
plugins:
  #- gmusic
  #- lyrics
  #- replaygain
- chroma
- convert
- duplicates
- edit
- fetchart
- inline
- lastimport
- missing
- random
- the

import:
  move: yes
  copy: no
  link: no
  hardlink: no
  resume: ask
  incremental: no
  log: ~/.cache/beets.log
  autotag: yes
  from_scratch: yes
  default_action: apply
  detail: yes
  duplicate_action: keep

pathfields:
  always_format: u'%s' % (format,) if format is not None and format != '' else path[:-3]
  disc_and_track: u'%02i.%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)

paths:
  default: Sorted/Music/%the{${albumartist}}/%if{${year},${year}-}${album}/%if{${track},${disc_and_track}-}$title
  singleton: Sorted/Music/%if{${year},${year}-}%the{${artist}}/${title}
  comp: Sorted/Music/%if{${year},${year}-}${album}/%if{${track},${disc_and_track}-}%if{${artist},%the{${artist}}-}${title}

clutter: [Thumbs.DB, .DS_Store, cover.*]
ignore:
- .*
- '*~'
- System Volume Information
- lost+found
ignore_hidden: yes

replace:
  '[\\/]': _
  ^\.: _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  \.$: _
  \s+$: ''
  ^\s+: ''
  ^-: _
  '[^a-zA-Z0-9-.]+': _
path_sep_replace: _
asciify_paths: yes
art_filename: cover

threaded: yes
timeout: 5.0
per_disc_numbering: yes
verbose: 0
original_date: yes

lastfm:
  user: dontpanic
