library: ~/Music/library.db
directory: ~/Music
plugins:
  #- gmusic
  #- replaygain
  #- lyrics
- chroma
- convert
- edit
- fetchart
- lastimport
- random
- the

import:
  move: yes
  copy: no
  link: no
  hardlink: no
  resume: ask
  incremental: no
  log: ~/.cache/beets.log
  autotag: yes
  from_scratch: yes
  default_action: apply
  detail: yes
  duplicate_action: ask

paths:
  default: Sorted/Albums/Music.%lower{${format}}/%the{${albumartist}}/%if{${year},${year}-}${album}%aunique{}/%if{${disc} > 1,Disc_${disc}}/%if{${track},${track}-}$title
  singleton: Sorted/Single/Music.%lower{${format}}/%if{${year},${year}-}%the{${artist}}/${title}
  comp: Sorted/Comp/Music.%lower{${format}}/%if{${year},${year}-}${album}%aunique{}/%if{${disc} > 1,Disc_${disc}}/%if{${track},${track}-}%if{${artist},%the{${artist}}-}${title}

clutter: [Thumbs.DB, .DS_Store, cover.jpg, cover.png]
ignore:
- .*
- '*~'
- System Volume Information
- lost+found
ignore_hidden: yes

replace:
  '[\\/]': _
  ^\.: _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  \.$: _
  \s+$: ''
  ^\s+: ''
  ^-: _
  '[^a-zA-Z0-9-.]+': _
path_sep_replace: _
asciify_paths: yes
art_filename: cover

threaded: yes
timeout: 5.0
per_disc_numbering: yes
verbose: 0
original_date: yes

lastfm:
  user: dontpanic
