#!/bin/bash
#
# To use this filter with less, define LESSOPEN:
# export LESSOPEN="|/usr/bin/lesspipe.sh %s"
#
# The script should return zero if the output was valid and non-zero
# otherwise, so less could detect even a valid empty output
# (for example while uncompressing gzipped empty file).
# For backward-compatibility, this is not required by default. To turn
# this functionality there should be another vertical bar (|) straight
# after the first one in the LESSOPEN environment variable:
# export LESSOPEN="||/usr/bin/lesspipe.sh %s"

if [ ! -e "$1" ] ; then
	exit 1
fi

# This is what is calling us in /usr/bin/lessopen.sh.  Ergo we should return 0 if we were able to filter the file, otherwise return non-zero
#if [ -x ~/.lessfilter ]; then
#	~/.lessfilter "$1"
#	if [ $? -eq 0 ]; then
#		exit 0
#	fi
#fi

# Apply redirection to the current shell
exec 2>/dev/null

source "${HOME}/dot-files/bash_common.sh"
log "$(callstack)"

exit_status=-1
case "$1" in
	*.log)
		colourise.py "$1"
		exit_status=$?
		log "Colourised $1 for less: colourise.py $1; Returned: $exit_status"
		;;
	*)
		pygmentize -f terminal "$1"
		exit_status=$?
		log "Pygmentizing $1 for less: pygmentize -f terminal $1; Returned: $exit_status"
		;;
esac
exit $exit_status
